# Generated by Django 5.2.15 on 2026-06-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('matched_query', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fire', 'Fire'), ('Flood / Rain Damage', 'Flood / Rain Damage'), ('Road Accident', 'Road Accident'), ('Infrastructure Failure', 'Infrastructure Failure'), ('Power Outage', 'Power Outage'), ('Health / Food Safety', 'Health / Food Safety'), ('Public Safety', 'Public Safety'), ('Other', 'Other')], default='Other', max_length=100)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district_city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_confidence', models.CharField(default='Low', max_length=50)),
                ('review_status', models.CharField(choices=[('Needs Review', 'Needs Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Edited', 'Edited')], default='Needs Review', max_length=50)),
                ('duplicate_score', models.FloatField(default=0)),
                ('is_possible_duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='incidents.rawarticle')),
            ],
        ),
    ]
