# Generated by Django 5.2.15 on 2026-06-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawarticle',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
